# Generated by Django 4.2.15 on 2025-01-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
